export const FETCH_TEMPLATE_REQUEST = 'FETCH_TEMPLATE_REQUEST'
export const FETCH_TEMPLATE_SUCCESS = 'FETCH_TEMPLATE_SUCCESS'
export const FETCH_TEMPLATE_FAILURE = 'FETCH_TEMPLATE_FAILURE'
export const SHOW_TEMPLATE_ALERT = 'SHOW_TEMPLATE_ALERT'

